{"name": "test_isInMain", "status": "broken", "statusDetails": {"message": "TypeError: exists() takes 1 positional argument but 2 were given", "trace": "self = <test_login.TestLogin object at 0x0000027CABE66970>\n\n    def test_isInMain(self):\n>       exists(imgDict['main_view'],\"不在主界面\")\nE       TypeError: exists() takes 1 positional argument but 2 were given\n\nmodules\\function\\login\\test_login.py:35: TypeError"}, "start": 1750069479375, "stop": 1750069479375, "uuid": "22d62d40-670c-46d9-9302-3a7a7a33d774", "historyId": "3fc3eee673628386db2d5c757bc260f6", "testCaseId": "3fc3eee673628386db2d5c757bc260f6", "fullName": "modules.function.login.test_login.TestLogin#test_isInMain", "labels": [{"name": "parentSuite", "value": "modules.function.login"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-AQCH3I7"}, {"name": "thread", "value": "1440-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "modules.function.login.test_login"}]}