{"name": "test_isInMain", "status": "broken", "statusDetails": {"message": "TypeError: exists_img() takes 1 positional argument but 2 were given", "trace": "self = <test_login.TestLogin object at 0x00000204FD4368E0>\n\n    def test_isInMain(self):\n>       exists_img(imgDict['main_view'],\"不在主界面\")\nE       TypeError: exists_img() takes 1 positional argument but 2 were given\n\nmodules\\function\\login\\test_login.py:35: TypeError"}, "start": 1750069624678, "stop": 1750069624678, "uuid": "ecb9a93e-f53c-454b-bb38-dad3cbafae6f", "historyId": "3fc3eee673628386db2d5c757bc260f6", "testCaseId": "3fc3eee673628386db2d5c757bc260f6", "fullName": "modules.function.login.test_login.TestLogin#test_isInMain", "labels": [{"name": "parentSuite", "value": "modules.function.login"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-AQCH3I7"}, {"name": "thread", "value": "30276-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "modules.function.login.test_login"}]}